linters:
  enable:
    - gosec
    - thelper
    - gci
    - nilerr
  disable:
    # TODO: Re-enable no-ctx when everything is moved to contexts
    - noctx
    - exhaustruct
    - exhaustive
    - testpackage
    - musttag
    - godox
    - godot
    - depguard
    - dupword
    - dupl
    - wsl
    - wrapcheck
    - varnamelen
    - tagliatelle
    - gocognit
    - gocyclo
    - cyclop
    - lll
    - ireturn
    - gochecknoglobals
    - funlen
    - gochecknoinits
    - iface
    - interfacebloat
    - maintidx
    - nestif
    - nlreturn
    - stylecheck
    - revive
    - goconst
    - forbidigo
    # Dynamic errors, may turn this on later
    - err113
    # Magic number may turn on later
    - mnd
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused