name: "Go Unit Tests"
description: |
  Run Go unit tests

runs:
  using: composite
  steps:
    # Setup checkout of Git
    - uses: actions/checkout@v4
    # Setup Go
    - uses: actions/setup-go@v5
      with:
        go-version: '>=1.22'
    # Run a local testnet in the background. After this action runs the local testnet
    # should be up and queryable. This also installs node and pnpm for us.
    - uses: aptos-labs/actions/run-local-testnet@main
      with:
        PNPM_VERSION: 8.9.0
    # Run unit tests

    - shell: bash
      run: |
        if [ "x$(git status -uno -s)x" != "xx" ]; then git status; echo NOT CLEAN; exit 1; fi
    - shell: bash
      run: 'go test ./...'
