name: gofumpt
env:
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

on:
  push:
    branches:
      - main
      - master
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ env.GIT_SHA }}
          persist-credentials: false
      - uses: ./.github/actions/run-gofumpt
